Remove the build hacks.
These are needed any more as the toolchain can now build a
complete output file via a normal clang invocation.

diff --git a/prboom-2.5.0/configure b/prboom-2.5.0/configure
--- a/prboom-2.5.0/configure
+++ b/prboom-2.5.0/configure
@@ -2868,7 +2868,7 @@ test "$ac_cv_exeext" = no && ac_cv_exeext=
 else
   ac_file=''
 fi
-ac_file=a.out
+
 { echo "$as_me:$LINENO: result: $ac_file" >&5
 echo "${ECHO_T}$ac_file" >&6; }
 if test -z "$ac_file"; then
@@ -2953,12 +2953,12 @@ for ac_file in conftest.exe conftest conftest.*; do
     * ) break;;
   esac
 done
-#else
-#  { { echo "$as_me:$LINENO: error: cannot compute suffix of executables: cannot compile and link
-#See \`config.log' for more details." >&5
-#echo "$as_me: error: cannot compute suffix of executables: cannot compile and link
-#See \`config.log' for more details." >&2;}
-#   { (exit 1); exit 1; }; }
+else
+  { { echo "$as_me:$LINENO: error: cannot compute suffix of executables: cannot compile and link
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot compute suffix of executables: cannot compile and link
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 rm -f conftest$ac_cv_exeext
diff --git a/sdlquake-1.0.9/configure b/sdlquake-1.0.9/configure
--- a/sdlquake-1.0.9/configure
+++ b/sdlquake-1.0.9/configure
@@ -1011,9 +1011,9 @@ ac_link='${CC-cc} -o conftest${ac_exeext} $CFLAGS $CPPFLAGS $LDFLAGS conftest.$a
 cross_compiling=$ac_cv_prog_cc_cross
 
 echo "$ac_t""$ac_cv_prog_cc_works" 1>&6
-#if test $ac_cv_prog_cc_works = no; then
-#  { echo "configure: error: installation or configuration problem: C compiler cannot create executables." 1>&2; exit 1; }
-#fi
+if test $ac_cv_prog_cc_works = no; then
+  { echo "configure: error: installation or configuration problem: C compiler cannot create executables." 1>&2; exit 1; }
+fi
 echo $ac_n "checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler""... $ac_c" 1>&6
 echo "configure:1019: checking whether the C compiler ($CC $CFLAGS $LDFLAGS) is a cross-compiler" >&5
 echo "$ac_t""$ac_cv_prog_cc_cross" 1>&6
